name: Upload to Databricks using API

on: 
  push:
    branches: main
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    environment:
      name: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Build Artifact
      uses: actions/upload-artifact@v4.2.0
      with:
        name: Build_Artifacts
        path: |
          ${{ github.workspace }}
          !**/Common/**
          !**/.github/**
          !**/.git/**
          !**/README.md

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: Build_Artifacts
        path: "${{github.workspace}}/artifacts"
      
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: databricks-import-directory
      uses: microsoft/databricks-import-directory@v1.0.0      
      with:
        databricks-host: "https://adb-3620630908047238.18.azuredatabricks.net"
        databricks-token: ${{ secrets.DB_TOKEN }} 
        local-path: "${{ github.workspace }}/artifacts"
        remote-path: "/Shared/output/"
