name: Python Package using Conda

on: 
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Uncomment the following steps if you need to use Conda
    # - name: Add conda to system path
    #   run: |
    #     echo $CONDA/bin >> $GITHUB_PATH
    # - name: Install dependencies
    #   run: conda env update --file environment.yml --name base

    # Add your other steps here (linting, testing, etc.)
    
    - name: Running python Script
      run: python ./app.py

  docker:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub 
      uses: docker/login-action@v3 
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: rishabh1501/learn-cicd
