name: Upload to Databricks using api

on: 
  push:
    branches: main
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: ["ubuntu-latest"]
        # python-version: ["3.10", "3.11", "3.12"]
        python-version: ["3.10"]
    environment:
      name: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build Artifact
      uses: actions/upload-artifact@v4.2.0
      with:
        name: Build_Artifacts
        path: |
          ${{ github.workspace }}
          !**/Common/**
          !**/.github/**
          !**/README.md
    
    - name: Install Databricks-CLI
      uses: microsoft/databricks-cli-install 

    - name: databricks-import-directory
      uses: microsoft/databricks-import-directory@v1.0.0
      with:
        databricks-host: https://adb-3620630908047238.18.azuredatabricks.net
        databricks-token: ${{ secrets.DB_TOKEN }} 
        local-path: "{{ github.workspace }}/"
        remote-path: "/"
