name: Upload Files to Databricks Workspace

on: 
  push:
    branches: main
    # branches: fractal-develop

jobs:
  build-and-deploy:
    environment:
      name: dev
    runs-on: ubuntu-latest

    steps: 
    - name: Variables Used in Workflow
      run: |
        echo Databricks Host: ${{ vars.DATABRICKS_HOST }}
        echo Remote Save Location: "${{ vars.REMOTE_FILE_PATH }}"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
      
    # - name: install-databricks-cli
    #   run: |
    #     curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
    #   shell: bash


    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az --version

    - name: Installing Databricks CLI
      run: |
        chmod +x ${{ github.workspace }}/databricks_cli_install.sh
        ${{ github.workspace }}/databricks_cli_install.sh
      shell: bash

    - name: Import Code to Databricks
      run: |
        rsync -av --exclude={.git,.github,README.md,.gitignore} "${{ github.workspace }}/" "${LOCAL_FILE_PATH}"

        databricks workspace import-dir --overwrite "${LOCAL_FILE_PATH}" "${REMOTE_FILE_PATH}" --debug

      env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DB_TOKEN }}
          LOCAL_FILE_PATH: "/tmp/temp_databricks/"
          # LOCAL_FILE_PATH: "${{ github.workspace }}/final_code/"
          REMOTE_FILE_PATH: "${{ vars.REMOTE_FILE_PATH }}"